name: Docker
on: [pull_request, workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Dockerfile
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false

      - name: Login to docker registry
        if: github.ref == 'refs/heads/main'
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

      - name: Push to docker registry
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.ORGANIZATION }}/${{ secrets.REPO }}:latest